# Generated by Django 4.1.7 on 2023-03-31 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_alter_genbankrecord_accession_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="data_files")),
            ],
        ),
    ]
